### ISSUE TITLE
Can not serve root dirs

### ISSUE THREAD

**Issue by F1LT3R** [markserv/markserv#46]
Described here: https://github.com/F1LT3R/markserv/issues/38#issuecomment-386219140

PR: https://github.com/F1LT3R/markserv/pull/45

**Comment by F1LT3R** [comment]
This should be fixed now.

Could you `npm i -g markserv@1.7.1` and `markserv /docs` to see if it works for you?

You should also be able to `markserv $(pwd)` from any directory, which will access the current directory via the absolute path instead of the relative path.

**Comment by m2acgi** [comment]
It still not work after 1.7.1 installed. The stdout says it serve **/root** when I serve **/docs**.

![2018-05-04 09_22_20](https://user-images.githubusercontent.com/34497122/39609746-c56c5fe4-4f7d-11e8-9e9b-ca0c0aeb7f59.png)
![2018-05-04 09_23_15](https://user-images.githubusercontent.com/34497122/39609747-c86cdd04-4f7d-11e8-95bc-2fbac5c9466a.png)

**Comment by F1LT3R** [comment]
What if you use /docs as your first argument? Ie: `markserv /docs --port 80 --address 0.0.0.0 --verbose`

**Comment by m2acgi** [comment]
It's the same as before.

root@debian-9:# **pwd**
**/root**
root@debian-9:# **markserv /docs --port 80 --address 0.0.0.0 --verbose**
  Markserv   address: http://0.0.0.0:80
  Markserv   path: **/root**
  Markserv   livereload: communicating on port: 35729
  Markserv   process: your pid is: 2348
  Markserv   stop: press [Ctrl + C] or type "sudo kill -9 2348"
  ? GitHub   Contribute on Github - github.com/f1lt3r/markserv
 ?● PATREON  Help support Markserv - Become a Patreon! patreon.com/f1lt3r

**Comment by F1LT3R** [comment]
I'll boot up Debian here in the morning. That should be quicker than me trying to fix what you are seeing on Debian with me using macOS. :)

**Comment by ChenYingChou** [comment]
Fix it as follows:

```patch
diff --git a/lib/cli.js b/lib/cli.js
index 835467f..bcced5a 100755
--- a/lib/cli.js
+++ b/lib/cli.js
@@ -25,6 +25,8 @@ flags.version(pkg.version)
        flags.$pathProvided = true
        if (flags.dir[0] !== '/') {
            flags.dir = path.normalize(path.join(cwd, serverPath))
+       } else {
+           flags.dir = serverPath;
        }
    }).parse(process.argv)

```

**Comment by damusix** [comment]
^ that works. @ChenYingChou you make PR? I can make PR. Or will maintainers make PR?

**Comment by DenIrkhin** [comment]
Thank You for nice module.

I have v1.12.3 but error with folder is still there.
As the result I can run markserv from directory where I have my .md files.

The fix of @ChenYingChou works perfectly.
Please include the fix in new version.

**Comment by F1LT3R** [comment]
Someone want to submit a PR for this? I am unable to test this scenario so it would be better that someone who can test it, submits the PR.

**Comment by DenIrkhin** [comment]
in 1.13.1 it works fine - Thank You
